image:
  #- Ubuntu
  #- Visual Studio 2015
  - Visual Studio 2017
  #- Visual Studio 2019

clone_folder: c:\lmath

configuration: Release

environment:
  matrix:
    #- cmake_arch: x86
    - cmake_arch: x64

for:
-
  matrix:
    only:
      - image: Ubuntu
  
  clone_folder: ~/lmath
  build_script:
    - mkdir build; cd build
    - cmake -DCMAKE_BUILD_TYPE=Release $extra_cmake_flags ..
    - make -j2
 
# skip unsupported combinations
init:
  - cmd: set arch=
  - cmd: if "%cmake_arch%"=="x64" ( set arch= Win64)
  - cmd: echo %arch%
  - cmd: echo %APPVEYOR_BUILD_WORKER_IMAGE%
  - cmd: if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2017" ( set generator="Visual Studio 15 2017%arch%" )
  - cmd: if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2019" ( set generator="Visual Studio 16 2019%arch%" )
  - cmd: echo %generator%
  - sh: if [ "$cmake_arch" = "x86" ]; then export extra_cmake_flags=-DCMAKE_CXX_FLAGS=-m32; sudo apt-get install -y g++-multilib; fi;

before_build:
- cmd: |-
    c:
    cd c:\lmath
    mkdir build
    cd build
    cmake --version
    cmake .. -G %generator%
build:
  project: c:\lmath\build\lmath.sln
  verbosity: minimal
  parallel: true

test:
  # only assemblies to test
  assemblies:
    only:
      - build\Test\Release\Test.exe
